import type { ParameterMetadata, TtsModeMetadata, TtsSpeakerOption } from "./types";

export const ttsModes: readonly TtsModeMetadata[] = [
  {
    value: "preset",
    label: "Preset",
    description: "Use one of the server-supported preset speakers.",
  },
  {
    value: "clone",
    label: "Voice clone",
    description: "Upload reference audio and reference text as multipart/form-data.",
  },
  {
    value: "design",
    label: "Voice design",
    description: "Send a JSON voice prompt for server-side voice design.",
  },
] as const;

export const ttsResponseFormats = ["wav", "mp3", "aac", "opus", "flac", "pcm"] as const;

export const ttsLanguageOptions = [
  "",
  "English",
  "Chinese",
  "Japanese",
  "Korean",
  "German",
  "French",
  "Russian",
  "Portuguese",
  "Spanish",
  "Italian",
] as const;

export const ttsSpeakerOptions: readonly TtsSpeakerOption[] = [
  { value: "serena", label: "Serena" },
  { value: "vivian", label: "Vivian" },
  { value: "uncle-fu", label: "Uncle Fu" },
  { value: "ryan", label: "Ryan" },
  { value: "aiden", label: "Aiden" },
  { value: "ono-anna", label: "Ono Anna" },
  { value: "sohee", label: "Sohee" },
  { value: "eric", label: "Eric" },
  { value: "dylan", label: "Dylan" },
] as const;

export const ttsParameterMetadata: ParameterMetadata[] = [
  {
    name: "mode",
    label: "Mode",
    defaultValue: "preset",
    description: "Voice generation mode used to select preset, clone, or design request shape.",
    required: true,
    supported: true,
    options: ttsModes.map((mode) => mode.value),
  },
  {
    name: "model",
    label: "Model",
    defaultValue: "",
    description: "TTS model identifier to use for speech synthesis.",
    required: true,
    supported: true,
  },
  {
    name: "input",
    label: "Input",
    defaultValue: "",
    description: "Text to synthesize. The server rejects empty input.",
    required: true,
    supported: true,
  },
  {
    name: "language",
    label: "Language",
    defaultValue: "",
    description: "Optional spoken language hint. Leave blank to use backend automatic language selection.",
    required: false,
    supported: true,
    options: ttsLanguageOptions,
  },
  {
    name: "response_format",
    label: "Response format",
    defaultValue: "wav",
    description: "Audio response format returned by the backend.",
    required: false,
    supported: true,
    options: ttsResponseFormats,
  },
  {
    name: "speaker",
    label: "Speaker",
    defaultValue: "serena",
    description: "Preset speaker name sent as the OpenAI-compatible voice field.",
    required: true,
    supported: true,
    options: ttsSpeakerOptions.map((speaker) => speaker.value),
  },
  {
    name: "reference_audio",
    label: "Reference audio",
    defaultValue: "",
    description: "Reference audio file for voice clone requests.",
    required: false,
    supported: true,
    notice: "Clone mode sends reference_audio as multipart/form-data; do not set Content-Type manually.",
  },
  {
    name: "reference_text",
    label: "Reference text",
    defaultValue: "",
    description: "Transcript matching the clone reference audio.",
    required: false,
    supported: true,
    notice: "Clone mode requires reference text on the server; blank values are omitted from previews.",
  },
  {
    name: "voice_prompt",
    label: "Voice prompt",
    defaultValue: "",
    description: "Voice design prompt describing the target voice.",
    required: false,
    supported: true,
    notice: "Design mode sends voice_prompt in the JSON request body.",
  },
  {
    name: "speed",
    label: "Speed",
    defaultValue: "1.0",
    description: "Speech speed multiplier.",
    required: false,
    supported: true,
    notice: "The server currently accepts only 1.0 for speed.",
  },
  {
    name: "seed",
    label: "Seed",
    defaultValue: "42",
    description: "Optional numeric generation seed.",
    required: false,
    supported: true,
  },
  {
    name: "temperature",
    label: "Temperature",
    defaultValue: "0.7",
    description: "Positive sampling temperature.",
    required: false,
    supported: true,
  },
  {
    name: "top_k",
    label: "Top K",
    defaultValue: "20",
    description: "Positive top_k sampling limit.",
    required: false,
    supported: true,
  },
  {
    name: "top_p",
    label: "Top P",
    defaultValue: "0.8",
    description: "Nucleus sampling value between 0 and 1 inclusive.",
    required: false,
    supported: true,
  },
  {
    name: "repetition_penalty",
    label: "Repetition penalty",
    defaultValue: "1.05",
    description: "Positive penalty applied to repeated generated tokens.",
    required: false,
    supported: true,
  },
  {
    name: "max_length",
    label: "Max length",
    defaultValue: "2048",
    description: "Positive maximum generation length.",
    required: false,
    supported: true,
  },
];
