[server]
bind = "0.0.0.0:9090"
max_upload_size = "100M"

[models]
dir = "../../data/models"
source = "auto"
max_loaded = 2

[services.asr]
enabled = true
default_model = "qwen3-asr-0.6b"
device = "auto"
available_models = ["qwen3-asr-0.6b", "qwen3-asr-1.7b"]
idle_timeout = "10m"
max_loaded = 1

[services.tts]
enabled = true
default_model = "qwen3-tts-0.6b-custom-voice"
device = "auto"
available_models = [
  "qwen3-tts-0.6b-base",
  "qwen3-tts-0.6b-custom-voice",
  "qwen3-tts-1.7b-base",
  "qwen3-tts-1.7b-custom-voice",
  "qwen3-tts-1.7b-voice-design",
]
idle_timeout = "10m"
max_loaded = 1
format = "wav"

[services.ocr]
enabled = true
default_model = "PaddlePaddle/PP-OCRv6_tiny"
available_models = [
  "PaddlePaddle/PP-OCRv5_mobile",
  "PaddlePaddle/PP-OCRv5_server",
  "PaddlePaddle/PP-OCRv6_tiny",
  "PaddlePaddle/PP-OCRv6_small",
  "PaddlePaddle/PP-OCRv6_medium"
]
layout_default_model = "PaddlePaddle/PP-DocLayoutV3"
layout_available_models = ["PaddlePaddle/PP-DocLayoutV3"]
device = "auto"
idle_timeout = "10m"
max_loaded = 1
format = "json"

[services.ocr-vl]
enabled = true
default_model = "PaddlePaddle/PaddleOCR-VL-1.6"
available_models = [
  "PaddlePaddle/PaddleOCR-VL-1.5",
  "PaddlePaddle/PaddleOCR-VL-1.6",
]
layout_default_model = "PaddlePaddle/PP-DocLayoutV3"
layout_available_models = ["PaddlePaddle/PP-DocLayoutV3"]
device = "auto"
idle_timeout = "10m"
max_loaded = 1
format = "markdown"

[auth]
# api_key = "change-me"
